spring:
  datasource:
    url: jdbc:${DB_ENGINE}://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
  logging:
    level:
      root: info
  flyway:
    schemas: ${DB_SCHEMA}
    enabled: true

server:
  port: 8080
